services:
  - type: web
    name: horeca-planner
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npx prisma db push --accept-data-loss && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      - key: CRON_SECRET
        sync: false
      - key: SUPPORT_EMAIL
        sync: false
